kind: Deployment
apiVersion: apps/v1
metadata:
  name: spring-cont
  namespace: default
  labels:
    appgroup: ''
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-cont
      version: v1
  template:
    metadata:
      labels:
        app: spring-cont
        version: v1
    spec:
      containers:
        - name: container-spring
          image: swr.ap-southeast-3.myhuaweicloud.com/yatas-test/spring-test:${BUILDNUMBER}
          resources:
            limits:
              cpu: 250m
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 512Mi
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      imagePullSecrets:
        - name: default-secret
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
